### ISSUE TITLE
🐛 Fix: develop 빌드 실패 — PreviewStudyScheduleRepository 프로토콜 요구 누락

### ISSUE THREAD

**Issue by jwon0523** [UMC-PRODUCT/umc-product-iOS#1063]
## 🐛 문제 상황

`develop` 이 빌드되지 않습니다. `ActivityPresentation` 컴파일 실패:

```
StudyScheduleRegistrationPreviewSupport.swift:41:13: error:
  type 'PreviewStudyScheduleRepository' does not conform to protocol 'StudyRepositoryProtocol'
  note: protocol requires function 'fetchStudyGroupNames()'
  note: protocol requires function 'fetchStudyMemberSubmissions(studyGroupId:weekNos:cursor:size:)'
```

## 🔍 원인

머지 순서로 생긴 semantic conflict 입니다. 두 PR 이 각자 브랜치에서는 통과했지만 합쳐지면서 깨졌습니다.

| PR | 커밋 | 한 일 |
|----|------|------|
| #1059 | `2e49b215` | `StudyRepositoryProtocol` 에 `fetchStudyGroupNames()` / `fetchStudyMemberSubmissions(...)` **추가** |
| #1061 | `d42be765` | `PreviewStudyScheduleRepository` **추가** — 위 2개 미구현 |

#1061 이 #1059 보다 먼저 분기해 새 프로토콜 요구를 보지 못한 상태로 각각 머지됐습니다.
`develop` CI 도 #1061 머지 시점 실행이 `failure` 로 남아 있습니다.

현재 열려 있는 PR 들이 전부 같은 이유로 CI 가 빨간 상태입니다.

## ✅ 완료 조건

- [ ] `PreviewStudyScheduleRepository` 가 `StudyRepositoryProtocol` 을 완전히 충족
- [ ] `develop` 기준 `make build SCHEME=UMCApp` 성공
- [ ] `develop` CI 초록 복구

## 🧪 테스트 조건

> 프리뷰 전용 DEBUG 스텁이라 신규 단위 테스트 대상이 아닙니다. 컴파일 복구를 빌드로 검증합니다.

- [ ] `make test SCHEME=ActivityPresentation` 통과 확인
- [ ] 테스트 통과 후 `make build SCHEME=UMCApp` 빌드 성공
- [ ] 빌드 성공 후 PR 생성
